### PR TITLE
Add placeholder icon

### LINKED ISSUE #2: Add placeholder icon
Add Placeholder Icon along with placeholder text.

image

### PR DESCRIPTION
**Pull request by scgm0**
Closes #2

### CODE REVIEW

**Comment by dhruv8sh** [comment]
Works flawlessly, great job on this.
Although, I was thinking when the placeholder icon is not being used, the icon of the current activity must be used in case anyone wants to use it. I also have a couple other nitpicks like changing "PlaceholderIcon:" to " Placeholder icon:".

I will create a pull request.

**Comment by dhruv8sh** [comment]
Some other thoughts:
 - Only make the placeholder icon editable if placeholder text is set, otherwise show the activities icon. (Could be controversial among KDE users though but in my opinion it doesn't make sense).
 - Option to fallback to placeholder icon if the current acitivity icon is not present.

**Comment by scgm0** [comment]
> Some other thoughts:
> 
>     * Only make the placeholder icon editable if placeholder text is set, otherwise show the activities icon. (Could be controversial among KDE users though but in my opinion it doesn't make sense).
> 
>     * Option to fallback to placeholder icon if the current acitivity icon is not present.

ok

**Comment by dhruv8sh** [comment]
> Only make the placeholder icon editable if placeholder text is set, otherwise show the activities icon.

This👆 because it would contradict the "Show when availaible" flag for icons, if not implemented.

One more **possible solution** could be to **place placeholder icon under this flag** and **enable it when the flag is checked**.
One more **flag to replace the activity icon** by the placeholder icon can be placed.

**Comment by scgm0** [comment]
> > Only make the placeholder icon editable if placeholder text is set, otherwise show the activities icon.仅当设置了占位符文本时才使占位符图标可编辑，否则显示活动图标。
> 
> This👆 because it would contradict the "Show when availaible" flag for icons, if not implemented.这是因为如果不实现，它将与图标的“可用时显示”标志相矛盾。
> 
> One more **possible solution** could be to **place placeholder icon button under this flag** and **enable it when the flag is checked**.另一种可能的解决方案是将占位符图标按钮放置在此标志下，并在选中该标志时启用它。 One more **flag to replace the activity icon** by the placeholder icon can be placed. 可以再放置一个标志来用占位符图标替换活动图标。
> 
> Thoughts? 想法？

Like this?
图片

**Comment by dhruv8sh** [comment]
image
Thoughts on this?

**Comment by scgm0** [comment]
> image Thoughts on this?对此有何想法？

good!

**Pull request merged**
